package com.safetys.nbyhpc.domain.model;

// Generated 2009-7-31 18:24:16 by Hibernate Tools 3.2.0.b9

/**
 * DaCompanyRefIndustry generated by hbm2java
 */
public class DaCompanyRefIndustry implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5011429039274823621L;

	private DaCompanyRefIndustryId id;

	private DaIndustryParameter daIndustryParameter;

	public DaCompanyRefIndustry() {
	}

	public DaCompanyRefIndustry(DaCompanyRefIndustryId id,
			DaIndustryParameter daIndustryParameter) {
		this.id = id;
		this.daIndustryParameter = daIndustryParameter;
	}

	public DaCompanyRefIndustryId getId() {
		return this.id;
	}

	public void setId(DaCompanyRefIndustryId id) {
		this.id = id;
	}

	public DaIndustryParameter getDaIndustryParameter() {
		return this.daIndustryParameter;
	}

	public void setDaIndustryParameter(DaIndustryParameter daIndustryParameter) {
		this.daIndustryParameter = daIndustryParameter;
	}

}
