package com.safetys.nbyhpc.domain.model;

// Generated 2011-1-8 11:07:39 by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.safetys.nbyhpc.domain.model.base.DaBaseModel;

/**
 * DaPipelineInfo generated by hbm2java
 */
public class DaPipelineInfo extends DaBaseModel {

	protected DaPipelineCompanyInfo daPipelineCompanyinfo;

	protected String name;//管道名称

	protected String lineType;//管道大类：油气管道(2)、燃气管道(1)
	
	protected int type;//管道种类：（1）油气管道：长输管道、城镇燃气管道、工业管道、港区内油气管道 （2）燃气管道：中低压燃气管道type=0

	protected int buildType;//管道铺设方式：架空， 埋地

	protected String startPoint;//管道起点

	protected String endPoint;//管道终点

	protected double length;//管道长度

	protected double pressure;//设计压力

	protected double maxPressure;//最高压力

	protected String medium;//传送介质

	protected double diameter;//管径

	protected double deep;//壁厚

	protected String material;//管道材质

	protected Date buildEndDate;//安装竣工时间

	protected Date beginUseDate;//投用时间

	protected boolean hasGhLicence;//是否办理规划许可
	
	protected String ghLicence;//规划许可证编号

	protected boolean hasScLicence;//安全生产许可证

	protected boolean hasYs;//是否通过竣工验收

	protected boolean hasDj;//是否妥协压力管道使用登记

	protected String djNum;//管道使用登记编号

	protected boolean hasSamePath;//实际路径是否与竣工图纸一致

	protected boolean hasCheck;//管道是否定期检验检测

	protected boolean hasCyrymjcs;

	protected boolean hasYjya;//是否制定应急预案

	protected boolean hasGlbhcs;//有无隔离保护措施

	protected boolean hasSign;//有无标志标识

	protected String checkPercent;//检查频率

	protected String fzr;

	protected String tbr;

	protected String address;

	protected Date inputDate;

	protected Long userId;

	protected Set daPipeTroubles = new HashSet(0);

	protected Set daPipeAttechs = new HashSet(0);
	
	private Set pipeNomalDangers = new HashSet(0);
	
	private Set pipeDangers = new HashSet(0);
	
	private double liquidTranAbility;
	
	private double gasTranAbility;
	
	private double mdNumSpan;//埋地 深度
	
	private boolean hasZfxt;//整改是否需政府协调
	
	private boolean hasCyczjcq;//是否有穿越城镇建成区管线
	
	private boolean hasKzjcpg;//是否开展检测和安全风险评估
	
	private String safetyLevelNo;//评估确定的安全风险等级
	
	private int notSamePathNum;//实际路径与竣工图纸不一致 
	
	private int rkmjPathNum;//管道穿越人员密集场所情况  
	
	private int aqfhPathNum;//管道安全防护区建设施工情况 
	
	private int cfssgPathNum;//管道穿曾发生安全事故情况 
	
	private int wzzyPathNum;//管道被违章占压情况 
	
	private int qtyhPathNum;//其他主要隐患 
	
	private Date kzjcpgDate;//评估时间
	
	private int yczjcqNum;//穿越长度

	private int repairCount;//已治理一般隐患数 - 非数据库字段
	
	private int unRepairCount;//未治理一般隐患数 - 非数据库字段
	
	private Long areaCode2;//管道区域- 非数据库字段
	
	private int count;//一般隐患数 - 非数据库字段
	
	private String realPath;//路径
	
	private String fileName;//文件名
	
	private DaCompany company;
	
	private String checkType;
	
	protected String pipeVersion;//页面大更改后的版本
	protected boolean fhcsgh;//建设和选址是否符合城乡规划
	protected double rymjcycd;//管道穿越人员密集场所情况   长度（Km）
	protected int rymjjlbfh;//与人员密集场所的安全距离不符合要求
	protected int aqbhjlbfh;//与建（构）筑物、铁路、公路、航道、港口、市政公用地下管线等的安全保护距离不符合要求
	protected int qtgxjc;//与市政公用等其他管线交叉
	protected int gxfbkj;//油气管道穿越其他管线封闭空间
	protected boolean jxsts;//新改扩是否进行“三同时”
	protected boolean tgfht;//江、河、湖泊等敏感区域管道是否提高压力设计等级、增加防护套等
	protected boolean xxjcxt;//是否配备压力、流量等信息不间断采集和监测系统
	protected boolean xlbjzz;//是否设置泄漏检测报警装置
	protected boolean szqdzz;//是否设置紧急切断装置
	protected boolean slxlbz;//经过封闭空间是否设立泄漏报警
	protected boolean jyjchg;//是否检验检测合格
	protected int dmgxwt;//地面管线存在腐蚀、破损、开裂、变形、老化和跑、冒、滴、漏
	protected boolean gzbzxt;//是否有故障下的安全保障设施和备用系统
	protected boolean nfxyh;//有无难以发现隐患的隐蔽工程
	protected boolean ylgddj;//是否办理压力管道使用登记
	protected String ylgddjLicense;//压力管道使用登记 编号
	protected boolean flfjdss;//是否按标准设计防雷、防静电设施
	protected boolean flfjdssjc;//防雷、防静电设施是否定期检查和检测
	protected boolean ffyjbhss;//是否采取有效的防腐绝缘与阴极保护措施
	protected boolean zdbhzz;//输油泵、加热炉、压缩机组等输油气生产设备、设施是否设置自动保护装置
	protected boolean zdbhzzjc;//自动保护装置是否定期检测
	protected boolean xhzd;//是否建立巡护制度
	protected int xhzdRate;//是否建立巡护制度(频率  次/天)
	protected String qxdw;//抢修队伍
	protected boolean spzd;//是否制定危险性作业审批制度并严格执行
	protected boolean gdtscl;//转产、停产、停用管道是否妥善处置
	protected boolean whbz;//发现第三方危害管道安全是否向政府部门报告
	protected boolean wtsjaz;//是否委托有资质单位进行设计、安装
	protected boolean aqybjba;//安全预评价是否备案
	protected boolean aqfxpg;//是否开展安全风险评估
	protected boolean zdyjya;//是否制定应急预案
	protected boolean yjyaba;//应急预案是否备案
	protected boolean dqzzyl;//是否定期组织演练
	protected boolean yjjydw;//是否建立应急救援队伍
	protected boolean pbqx;//是否配备相关抢险设备、器材和设施
	protected boolean aqsczrz;//是否建立并落实安全生产责任制
	protected boolean yhpczl;//是否定期开展隐患排查治理
	protected boolean xxllxt;//是否将隐患排查治理信息录入信息系统
	protected boolean rypx;//是否对相关人员进行培训
	protected boolean gdda;//是否建立管道档案
	protected boolean gdsjk;//是否进入规划部门管道数据库
	protected boolean toused;//是否在用


	public DaPipelineInfo() {
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getBeginUseDate() {
		return beginUseDate;
	}

	public void setBeginUseDate(Date beginUseDate) {
		this.beginUseDate = beginUseDate;
	}

	public Date getBuildEndDate() {
		return buildEndDate;
	}

	public void setBuildEndDate(Date buildEndDate) {
		this.buildEndDate = buildEndDate;
	}

	public int getBuildType() {
		return buildType;
	}

	public void setBuildType(int buildType) {
		this.buildType = buildType;
	}

	public String getCheckPercent() {
		return checkPercent;
	}

	public void setCheckPercent(String checkPercent) {
		this.checkPercent = checkPercent;
	}

	public Set getDaPipeAttechs() {
		return daPipeAttechs;
	}

	public void setDaPipeAttechs(Set daPipeAttechs) {
		this.daPipeAttechs = daPipeAttechs;
	}

	public DaPipelineCompanyInfo getDaPipelineCompanyinfo() {
		return daPipelineCompanyinfo;
	}

	public void setDaPipelineCompanyinfo(DaPipelineCompanyInfo daPipelineCompanyinfo) {
		this.daPipelineCompanyinfo = daPipelineCompanyinfo;
	}

	public Set getDaPipeTroubles() {
		return daPipeTroubles;
	}

	public void setDaPipeTroubles(Set daPipeTroubles) {
		this.daPipeTroubles = daPipeTroubles;
	}

	public double getDeep() {
		return deep;
	}

	public void setDeep(double deep) {
		this.deep = deep;
	}

	public double getDiameter() {
		return diameter;
	}

	public void setDiameter(double diameter) {
		this.diameter = diameter;
	}

	public String getDjNum() {
		return djNum;
	}

	public void setDjNum(String djNum) {
		this.djNum = djNum;
	}

	public String getEndPoint() {
		return endPoint;
	}

	public void setEndPoint(String endPoint) {
		this.endPoint = endPoint;
	}

	public String getFzr() {
		return fzr;
	}

	public void setFzr(String fzr) {
		this.fzr = fzr;
	}

	public boolean isHasCheck() {
		return hasCheck;
	}

	public void setHasCheck(boolean hasCheck) {
		this.hasCheck = hasCheck;
	}

	public boolean isHasCyrymjcs() {
		return hasCyrymjcs;
	}

	public void setHasCyrymjcs(boolean hasCyrymjcs) {
		this.hasCyrymjcs = hasCyrymjcs;
	}

	public boolean isHasDj() {
		return hasDj;
	}

	public void setHasDj(boolean hasDj) {
		this.hasDj = hasDj;
	}

	public boolean isHasGhLicence() {
		return hasGhLicence;
	}

	public void setHasGhLicence(boolean hasGhLicence) {
		this.hasGhLicence = hasGhLicence;
	}

	public boolean isHasGlbhcs() {
		return hasGlbhcs;
	}

	public void setHasGlbhcs(boolean hasGlbhcs) {
		this.hasGlbhcs = hasGlbhcs;
	}

	public boolean isHasSamePath() {
		return hasSamePath;
	}

	public void setHasSamePath(boolean hasSamePath) {
		this.hasSamePath = hasSamePath;
	}

	public boolean isHasScLicence() {
		return hasScLicence;
	}

	public void setHasScLicence(boolean hasScLicence) {
		this.hasScLicence = hasScLicence;
	}

	public boolean isHasSign() {
		return hasSign;
	}

	public void setHasSign(boolean hasSign) {
		this.hasSign = hasSign;
	}

	public boolean isHasYjya() {
		return hasYjya;
	}

	public void setHasYjya(boolean hasYjya) {
		this.hasYjya = hasYjya;
	}

	public boolean isHasYs() {
		return hasYs;
	}

	public void setHasYs(boolean hasYs) {
		this.hasYs = hasYs;
	}

	public Date getInputDate() {
		return inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

	public double getLength() {
		return length;
	}

	public void setLength(double length) {
		this.length = length;
	}

	public String getMaterial() {
		return material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public double getMaxPressure() {
		return maxPressure;
	}

	public void setMaxPressure(double maxPressure) {
		this.maxPressure = maxPressure;
	}

	public String getMedium() {
		return medium;
	}

	public void setMedium(String medium) {
		this.medium = medium;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getPressure() {
		return pressure;
	}

	public void setPressure(double pressure) {
		this.pressure = pressure;
	}

	public String getStartPoint() {
		return startPoint;
	}

	public void setStartPoint(String startPoint) {
		this.startPoint = startPoint;
	}

	public String getTbr() {
		return tbr;
	}

	public void setTbr(String tbr) {
		this.tbr = tbr;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getGhLicence() {
		return ghLicence;
	}

	public void setGhLicence(String ghLicence) {
		this.ghLicence = ghLicence;
	}

	public int getRepairCount() {
		return repairCount;
	}

	public void setRepairCount(int repairCount) {
		this.repairCount = repairCount;
	}

	public int getUnRepairCount() {
		return unRepairCount;
	}

	public void setUnRepairCount(int unRepairCount) {
		this.unRepairCount = unRepairCount;
	}

	public Set getPipeNomalDangers() {
		return pipeNomalDangers;
	}

	public void setPipeNomalDangers(Set pipeNomalDangers) {
		this.pipeNomalDangers = pipeNomalDangers;
	}

	public Set getPipeDangers() {
		return pipeDangers;
	}

	public void setPipeDangers(Set pipeDangers) {
		this.pipeDangers = pipeDangers;
	}

	public String getLineType() {
		return lineType;
	}

	public void setLineType(String lineType) {
		this.lineType = lineType;
	}

	public boolean isHasZfxt() {
		return hasZfxt;
	}

	public void setHasZfxt(boolean hasZfxt) {
		this.hasZfxt = hasZfxt;
	}

	public boolean isHasCyczjcq() {
		return hasCyczjcq;
	}

	public void setHasCyczjcq(boolean hasCyczjcq) {
		this.hasCyczjcq = hasCyczjcq;
	}

	public boolean isHasKzjcpg() {
		return hasKzjcpg;
	}

	public void setHasKzjcpg(boolean hasKzjcpg) {
		this.hasKzjcpg = hasKzjcpg;
	}

	public int getRkmjPathNum() {
		return rkmjPathNum;
	}

	public void setRkmjPathNum(int rkmjPathNum) {
		this.rkmjPathNum = rkmjPathNum;
	}

	public int getAqfhPathNum() {
		return aqfhPathNum;
	}

	public void setAqfhPathNum(int aqfhPathNum) {
		this.aqfhPathNum = aqfhPathNum;
	}

	public int getCfssgPathNum() {
		return cfssgPathNum;
	}

	public void setCfssgPathNum(int cfssgPathNum) {
		this.cfssgPathNum = cfssgPathNum;
	}

	public int getWzzyPathNum() {
		return wzzyPathNum;
	}

	public void setWzzyPathNum(int wzzyPathNum) {
		this.wzzyPathNum = wzzyPathNum;
	}

	public int getQtyhPathNum() {
		return qtyhPathNum;
	}

	public void setQtyhPathNum(int qtyhPathNum) {
		this.qtyhPathNum = qtyhPathNum;
	}

	public String getSafetyLevelNo() {
		return safetyLevelNo;
	}

	public void setSafetyLevelNo(String safetyLevelNo) {
		this.safetyLevelNo = safetyLevelNo;
	}

	public double getMdNumSpan() {
		return mdNumSpan;
	}

	public void setMdNumSpan(double mdNumSpan) {
		this.mdNumSpan = mdNumSpan;
	}

	public int getNotSamePathNum() {
		return notSamePathNum;
	}

	public void setNotSamePathNum(int notSamePathNum) {
		this.notSamePathNum = notSamePathNum;
	}

	public double getLiquidTranAbility() {
		return liquidTranAbility;
	}

	public void setLiquidTranAbility(double liquidTranAbility) {
		this.liquidTranAbility = liquidTranAbility;
	}

	public double getGasTranAbility() {
		return gasTranAbility;
	}

	public void setGasTranAbility(double gasTranAbility) {
		this.gasTranAbility = gasTranAbility;
	}

	public Date getKzjcpgDate() {
		return kzjcpgDate;
	}

	public void setKzjcpgDate(Date kzjcpgDate) {
		this.kzjcpgDate = kzjcpgDate;
	}

	public int getYczjcqNum() {
		return yczjcqNum;
	}

	public void setYczjcqNum(int yczjcqNum) {
		this.yczjcqNum = yczjcqNum;
	}

	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public String getRealPath() {
		return realPath;
	}

	public void setRealPath(String realPath) {
		this.realPath = realPath;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public DaCompany getCompany() {
		return company;
	}

	public void setCompany(DaCompany company) {
		this.company = company;
	}

	public String getCheckType() {
		return checkType;
	}

	public void setCheckType(String checkType) {
		this.checkType = checkType;
	}

	public Long getAreaCode2() {
		return areaCode2;
	}

	public void setAreaCode2(Long areaCode2) {
		this.areaCode2 = areaCode2;
	}

	public String getPipeVersion() {
		return pipeVersion;
	}

	public void setPipeVersion(String pipeVersion) {
		this.pipeVersion = pipeVersion;
	}

	public boolean isFhcsgh() {
		return fhcsgh;
	}

	public void setFhcsgh(boolean fhcsgh) {
		this.fhcsgh = fhcsgh;
	}

	public double getRymjcycd() {
		return rymjcycd;
	}

	public void setRymjcycd(double rymjcycd) {
		this.rymjcycd = rymjcycd;
	}

	public int getRymjjlbfh() {
		return rymjjlbfh;
	}

	public void setRymjjlbfh(int rymjjlbfh) {
		this.rymjjlbfh = rymjjlbfh;
	}

	public int getAqbhjlbfh() {
		return aqbhjlbfh;
	}

	public void setAqbhjlbfh(int aqbhjlbfh) {
		this.aqbhjlbfh = aqbhjlbfh;
	}

	public int getQtgxjc() {
		return qtgxjc;
	}

	public void setQtgxjc(int qtgxjc) {
		this.qtgxjc = qtgxjc;
	}

	public int getGxfbkj() {
		return gxfbkj;
	}

	public void setGxfbkj(int gxfbkj) {
		this.gxfbkj = gxfbkj;
	}

	public boolean isJxsts() {
		return jxsts;
	}

	public void setJxsts(boolean jxsts) {
		this.jxsts = jxsts;
	}

	public boolean isTgfht() {
		return tgfht;
	}

	public void setTgfht(boolean tgfht) {
		this.tgfht = tgfht;
	}

	public boolean isXxjcxt() {
		return xxjcxt;
	}

	public void setXxjcxt(boolean xxjcxt) {
		this.xxjcxt = xxjcxt;
	}

	public boolean isXlbjzz() {
		return xlbjzz;
	}

	public void setXlbjzz(boolean xlbjzz) {
		this.xlbjzz = xlbjzz;
	}

	public boolean isSzqdzz() {
		return szqdzz;
	}

	public void setSzqdzz(boolean szqdzz) {
		this.szqdzz = szqdzz;
	}

	public boolean isSlxlbz() {
		return slxlbz;
	}

	public void setSlxlbz(boolean slxlbz) {
		this.slxlbz = slxlbz;
	}

	public boolean isJyjchg() {
		return jyjchg;
	}

	public void setJyjchg(boolean jyjchg) {
		this.jyjchg = jyjchg;
	}

	public int getDmgxwt() {
		return dmgxwt;
	}

	public void setDmgxwt(int dmgxwt) {
		this.dmgxwt = dmgxwt;
	}

	public boolean isGzbzxt() {
		return gzbzxt;
	}

	public void setGzbzxt(boolean gzbzxt) {
		this.gzbzxt = gzbzxt;
	}

	public boolean isNfxyh() {
		return nfxyh;
	}

	public void setNfxyh(boolean nfxyh) {
		this.nfxyh = nfxyh;
	}

	public boolean isYlgddj() {
		return ylgddj;
	}

	public void setYlgddj(boolean ylgddj) {
		this.ylgddj = ylgddj;
	}

	public String getYlgddjLicense() {
		return ylgddjLicense;
	}

	public void setYlgddjLicense(String ylgddjLicense) {
		this.ylgddjLicense = ylgddjLicense;
	}

	public boolean isFlfjdss() {
		return flfjdss;
	}

	public void setFlfjdss(boolean flfjdss) {
		this.flfjdss = flfjdss;
	}

	public boolean isFlfjdssjc() {
		return flfjdssjc;
	}

	public void setFlfjdssjc(boolean flfjdssjc) {
		this.flfjdssjc = flfjdssjc;
	}

	public boolean isFfyjbhss() {
		return ffyjbhss;
	}

	public void setFfyjbhss(boolean ffyjbhss) {
		this.ffyjbhss = ffyjbhss;
	}

	public boolean isZdbhzz() {
		return zdbhzz;
	}

	public void setZdbhzz(boolean zdbhzz) {
		this.zdbhzz = zdbhzz;
	}

	public boolean isZdbhzzjc() {
		return zdbhzzjc;
	}

	public void setZdbhzzjc(boolean zdbhzzjc) {
		this.zdbhzzjc = zdbhzzjc;
	}

	public boolean isXhzd() {
		return xhzd;
	}

	public void setXhzd(boolean xhzd) {
		this.xhzd = xhzd;
	}

	public int getXhzdRate() {
		return xhzdRate;
	}

	public void setXhzdRate(int xhzdRate) {
		this.xhzdRate = xhzdRate;
	}

	public String getQxdw() {
		return qxdw;
	}

	public void setQxdw(String qxdw) {
		this.qxdw = qxdw;
	}

	public boolean isSpzd() {
		return spzd;
	}

	public void setSpzd(boolean spzd) {
		this.spzd = spzd;
	}

	public boolean isGdtscl() {
		return gdtscl;
	}

	public void setGdtscl(boolean gdtscl) {
		this.gdtscl = gdtscl;
	}

	public boolean isWhbz() {
		return whbz;
	}

	public void setWhbz(boolean whbz) {
		this.whbz = whbz;
	}

	public boolean isWtsjaz() {
		return wtsjaz;
	}

	public void setWtsjaz(boolean wtsjaz) {
		this.wtsjaz = wtsjaz;
	}

	public boolean isAqybjba() {
		return aqybjba;
	}

	public void setAqybjba(boolean aqybjba) {
		this.aqybjba = aqybjba;
	}

	public boolean isAqfxpg() {
		return aqfxpg;
	}

	public void setAqfxpg(boolean aqfxpg) {
		this.aqfxpg = aqfxpg;
	}

	public boolean isZdyjya() {
		return zdyjya;
	}

	public void setZdyjya(boolean zdyjya) {
		this.zdyjya = zdyjya;
	}

	public boolean isYjyaba() {
		return yjyaba;
	}

	public void setYjyaba(boolean yjyaba) {
		this.yjyaba = yjyaba;
	}

	public boolean isDqzzyl() {
		return dqzzyl;
	}

	public void setDqzzyl(boolean dqzzyl) {
		this.dqzzyl = dqzzyl;
	}

	public boolean isYjjydw() {
		return yjjydw;
	}

	public void setYjjydw(boolean yjjydw) {
		this.yjjydw = yjjydw;
	}

	public boolean isPbqx() {
		return pbqx;
	}

	public void setPbqx(boolean pbqx) {
		this.pbqx = pbqx;
	}

	public boolean isAqsczrz() {
		return aqsczrz;
	}

	public void setAqsczrz(boolean aqsczrz) {
		this.aqsczrz = aqsczrz;
	}

	public boolean isYhpczl() {
		return yhpczl;
	}

	public void setYhpczl(boolean yhpczl) {
		this.yhpczl = yhpczl;
	}

	public boolean isXxllxt() {
		return xxllxt;
	}

	public void setXxllxt(boolean xxllxt) {
		this.xxllxt = xxllxt;
	}

	public boolean isRypx() {
		return rypx;
	}

	public void setRypx(boolean rypx) {
		this.rypx = rypx;
	}

	public boolean isGdda() {
		return gdda;
	}

	public void setGdda(boolean gdda) {
		this.gdda = gdda;
	}

	public boolean isGdsjk() {
		return gdsjk;
	}

	public void setGdsjk(boolean gdsjk) {
		this.gdsjk = gdsjk;
	}

	public boolean isToused() {
		return toused;
	}

	public void setToused(boolean toused) {
		this.toused = toused;
	}

}
