package com.safetys.nbyhpc.domain.model;

// Generated 2011-1-8 11:07:39 by Hibernate Tools 3.2.0.b9

import com.safetys.nbyhpc.domain.model.base.DaBaseModel;

/**
 * DaPipeTrouble generated by hbm2java
 */
public class DaPipeTrouble extends DaBaseModel {

	private DaPipelineInfo daPipelineInfo;

	private int type;

	private String content;

	private String result;

	private Long userId;
	
	private int status;//0 为治理， 1：已治理
	
	private Long firstArea;

	private Long secondArea;

	private Long thirdArea;

	public DaPipeTrouble() {
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public DaPipelineInfo getDaPipelineInfo() {
		return daPipelineInfo;
	}

	public void setDaPipelineInfo(DaPipelineInfo daPipelineInfo) {
		this.daPipelineInfo = daPipelineInfo;
	}

	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Long getFirstArea() {
		return firstArea;
	}

	public void setFirstArea(Long firstArea) {
		this.firstArea = firstArea;
	}

	public Long getSecondArea() {
		return secondArea;
	}

	public void setSecondArea(Long secondArea) {
		this.secondArea = secondArea;
	}

	public Long getThirdArea() {
		return thirdArea;
	}

	public void setThirdArea(Long thirdArea) {
		this.thirdArea = thirdArea;
	}


}
