package com.safetys.nbyhpc.domain.model;

// Generated 2011-1-8 11:07:39 by Hibernate Tools 3.2.0.b9

import java.io.File;

import com.safetys.nbyhpc.domain.model.base.DaBaseModel;

/**
 * DaPipeAttech generated by hbm2java
 */
public class DaPipeAttech extends DaBaseModel {

	private DaPipelineInfo daPipelineInfo;

	private String title;

	private String content;

	private String attechFile;

	private int type;

	private Long userId;
	
	private File uploadFile;
	
	private String uploadFileFileName;
	
	private Long firstArea;

	private Long secondArea;

	private Long thirdArea;

	public DaPipeAttech() {
	}

	public String getAttechFile() {
		return attechFile;
	}

	public void setAttechFile(String attechFile) {
		this.attechFile = attechFile;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public DaPipelineInfo getDaPipelineInfo() {
		return daPipelineInfo;
	}

	public void setDaPipelineInfo(DaPipelineInfo daPipelineInfo) {
		this.daPipelineInfo = daPipelineInfo;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public File getUploadFile() {
		return uploadFile;
	}

	public void setUploadFile(File uploadFile) {
		this.uploadFile = uploadFile;
	}

	public String getUploadFileFileName() {
		return uploadFileFileName;
	}

	public void setUploadFileFileName(String uploadFileFileName) {
		this.uploadFileFileName = uploadFileFileName;
	}

	public Long getFirstArea() {
		return firstArea;
	}

	public void setFirstArea(Long firstArea) {
		this.firstArea = firstArea;
	}

	public Long getSecondArea() {
		return secondArea;
	}

	public void setSecondArea(Long secondArea) {
		this.secondArea = secondArea;
	}

	public Long getThirdArea() {
		return thirdArea;
	}

	public void setThirdArea(Long thirdArea) {
		this.thirdArea = thirdArea;
	}



}
