package com.safetys.nbyhpc.domain.model;

// Generated 2011-1-8 11:07:39 by Hibernate Tools 3.2.0.b9


/**
 * DaPipelineInfo generated by hbm2java
 */
public class DaYqPipelineInfo extends DaPipelineInfo {


}
