package com.safetys.nbyhpc.domain.model;

import java.util.Date;

import com.safetys.nbyhpc.domain.model.base.DaBaseModel;

// Generated 2012-11-6 15:59:30 by Hibernate Tools 3.2.0.b9

/**
 * TCoreCompany generated by hbm2java
 */
public class TCompany extends DaBaseModel  implements java.io.Serializable {
	/**
	 * 企业基础信息库
	 */
	private static final long serialVersionUID = -2335778146908423694L;
	private Long id;//编号
	private String companyName;
	private String regAddress;
	private String regArea;
	private Long firstArea;
	private Long secondArea;
	private Long thirdArea;
	private Long fouthArea;
	private Long fifthArea;
	private String businessAddress;
	private String zipCode;
	private String chemicalAddress;
	private String nationalEconomicType1;
	private String nationalEconomicType2;
	private String managementLevel1;
	private String managementLevel2;
	private String economicType1;
	private String economicType2;
	private Date establishmentDay;
	private String businessRegNum;
	private String orgCode;
	private Double regCapital;
	private String productionScale;
	
	private Double yearSales;
	private String legalPerson;
	private Double floorArea;
	private String principalPerson;
	private String principalSex;
	private String principalMobile;
	private String principalTelephone;
	private String principalSafetyCert;
	private Date principalSafetyValidity;
	private Date principalTrainDate;
	private String fax;
	private Integer enterprise;
	private Integer focusFireUnits;
	private Integer focusTownUnits;
	private Integer employeeQuotoNum;
	private Integer employeeActualNum;
	private Integer insuredNum;
	private String designOrg;
	private String constuctOrg;
	private String businessScope;
	private String majorProduct;
	private String middleProduct;
	private String productionCapacity;
	private String material;
	private String gatePic;
	private String workPic;
	private String state;
	private String longitude;
	private String dimensionality;
	private String safetyOrg;
	private Integer isMsds;
	private Date createTime;
	private Date modifyTime;
	private boolean deleted;
	private Integer safetyId;
	private String zjId;
	private String gsId;
	private Integer isGatherData;
	private String natinalRegulatoryCode1;
	private String natinalRegulatoryCode2;
	private String url;
	private String email;
	private String uuid;
	private String type;
	private String productionPurpose;
	private String regOrgCode;
	private String phone;
	private Date principalFirainDate;
	private Integer storageState;
	private Integer recordState;
	private String inSynFromDes;
	private String legalTelephone;
	private String CoverState;
	private String provinceCode;
	private String linkPerson;
	private String linkPhone;
	private String creditGrade;
	private String idCard;
	private Date birthday;
	private Date creditCancelTime;
	private Date cancelTime;
	private String education;
	private Integer isHidden;
	private Integer creditStatus;
	private String deptCode;
	private int flag;// 1工商注册号      2组织机构代码
	private Integer isSynchro;//，是否同步到中心库中标志
	
	private String aqscId;//安全状况表ID
	private String safetyMngPerson;
	private String safetyMngPersonPhone;
	
	private Long isSYN;// 是否与本地交互 1-交互 0-否
	private Long SYN_NO;// 同步号
	private String isUpdate;// 是否更新 0-否 1-是
	private String IS_HIDDEN;// 是否来源于隐藏系统 0－否 1－是
	
	private String securityPrincipalPerson; //安管负责人
	private String securityPrincipalTel;//安管负责人电话
	
	//是否高风险作业（1：是，0：否）
	private String isHighRiskWork;
	//高风险作业内容
	private String highRiskWork;
	
	//隐患企业创建世界
	private Date hiddenCompanyDate;
	
	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getRegAddress() {
		return regAddress;
	}

	public void setRegAddress(String regAddress) {
		this.regAddress = regAddress;
	}

	public Long getFirstArea() {
		return firstArea;
	}

	public void setFirstArea(Long firstArea) {
		this.firstArea = firstArea;
	}

	public Long getSecondArea() {
		return secondArea;
	}

	public void setSecondArea(Long secondArea) {
		this.secondArea = secondArea;
	}

	public Long getThirdArea() {
		return thirdArea;
	}

	public void setThirdArea(Long thirdArea) {
		this.thirdArea = thirdArea;
	}

	public Long getFouthArea() {
		return fouthArea;
	}

	public void setFouthArea(Long fouthArea) {
		this.fouthArea = fouthArea;
	}

	public Long getFifthArea() {
		return fifthArea;
	}

	public void setFifthArea(Long fifthArea) {
		this.fifthArea = fifthArea;
	}

	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getManagementLevel1() {
		return managementLevel1;
	}

	public void setManagementLevel1(String managementLevel1) {
		this.managementLevel1 = managementLevel1;
	}

	public String getManagementLevel2() {
		return managementLevel2;
	}

	public void setManagementLevel2(String managementLevel2) {
		this.managementLevel2 = managementLevel2;
	}

	public String getEconomicType1() {
		return economicType1;
	}

	public void setEconomicType1(String economicType1) {
		this.economicType1 = economicType1;
	}

	public String getEconomicType2() {
		return economicType2;
	}

	public void setEconomicType2(String economicType2) {
		this.economicType2 = economicType2;
	}

	public Date getEstablishmentDay() {
		return establishmentDay;
	}

	public void setEstablishmentDay(Date establishmentDay) {
		this.establishmentDay = establishmentDay;
	}

	public String getBusinessRegNum() {
		return businessRegNum;
	}

	public void setBusinessRegNum(String businessRegNum) {
		this.businessRegNum = businessRegNum;
	}

	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public Double getRegCapital() {
		return regCapital;
	}

	public void setRegCapital(Double regCapital) {
		this.regCapital = regCapital;
	}

	public Double getYearSales() {
		return yearSales;
	}

	public void setYearSales(Double yearSales) {
		this.yearSales = yearSales;
	}

	public String getLegalPerson() {
		return legalPerson;
	}

	public void setLegalPerson(String legalPerson) {
		this.legalPerson = legalPerson;
	}

	public Double getFloorArea() {
		return floorArea;
	}

	public void setFloorArea(Double floorArea) {
		this.floorArea = floorArea;
	}

	public String getPrincipalPerson() {
		return principalPerson;
	}

	public void setPrincipalPerson(String principalPerson) {
		this.principalPerson = principalPerson;
	}

	public String getPrincipalMobile() {
		return principalMobile;
	}

	public void setPrincipalMobile(String principalMobile) {
		this.principalMobile = principalMobile;
	}

	public String getPrincipalTelephone() {
		return principalTelephone;
	}

	public void setPrincipalTelephone(String principalTelephone) {
		this.principalTelephone = principalTelephone;
	}

	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	

	public Integer getEnterprise() {
		return enterprise;
	}

	public void setEnterprise(Integer enterprise) {
		this.enterprise = enterprise;
	}

	

	public Integer getFocusFireUnits() {
		return focusFireUnits;
	}

	public void setFocusFireUnits(Integer focusFireUnits) {
		this.focusFireUnits = focusFireUnits;
	}

	public Integer getFocusTownUnits() {
		return focusTownUnits;
	}

	public void setFocusTownUnits(Integer focusTownUnits) {
		this.focusTownUnits = focusTownUnits;
	}

	public String getRegArea() {
		return regArea;
	}

	public void setRegArea(String regArea) {
		this.regArea = regArea;
	}

	public String getBusinessAddress() {
		return businessAddress;
	}

	public void setBusinessAddress(String businessAddress) {
		this.businessAddress = businessAddress;
	}

	public String getChemicalAddress() {
		return chemicalAddress;
	}

	public void setChemicalAddress(String chemicalAddress) {
		this.chemicalAddress = chemicalAddress;
	}

	public String getNationalEconomicType1() {
		return nationalEconomicType1;
	}

	public void setNationalEconomicType1(String nationalEconomicType1) {
		this.nationalEconomicType1 = nationalEconomicType1;
	}

	public String getNationalEconomicType2() {
		return nationalEconomicType2;
	}

	public void setNationalEconomicType2(String nationalEconomicType2) {
		this.nationalEconomicType2 = nationalEconomicType2;
	}

	public String getProductionScale() {
		return productionScale;
	}

	public void setProductionScale(String productionScale) {
		this.productionScale = productionScale;
	}

	public String getPrincipalSex() {
		return principalSex;
	}

	public void setPrincipalSex(String principalSex) {
		this.principalSex = principalSex;
	}

	public String getPrincipalSafetyCert() {
		return principalSafetyCert;
	}

	public void setPrincipalSafetyCert(String principalSafetyCert) {
		this.principalSafetyCert = principalSafetyCert;
	}

	

	public Date getPrincipalSafetyValidity() {
		return principalSafetyValidity;
	}

	public void setPrincipalSafetyValidity(Date principalSafetyValidity) {
		this.principalSafetyValidity = principalSafetyValidity;
	}

	public Date getPrincipalTrainDate() {
		return principalTrainDate;
	}

	public void setPrincipalTrainDate(Date principalTrainDate) {
		this.principalTrainDate = principalTrainDate;
	}

	public Integer getEmployeeQuotoNum() {
		return employeeQuotoNum;
	}

	public void setEmployeeQuotoNum(Integer employeeQuotoNum) {
		this.employeeQuotoNum = employeeQuotoNum;
	}

	public Integer getEmployeeActualNum() {
		return employeeActualNum;
	}

	public void setEmployeeActualNum(Integer employeeActualNum) {
		this.employeeActualNum = employeeActualNum;
	}

	public Integer getInsuredNum() {
		return insuredNum;
	}

	public void setInsuredNum(Integer insuredNum) {
		this.insuredNum = insuredNum;
	}

	public String getDesignOrg() {
		return designOrg;
	}

	public void setDesignOrg(String designOrg) {
		this.designOrg = designOrg;
	}

	public String getConstuctOrg() {
		return constuctOrg;
	}

	public void setConstuctOrg(String constuctOrg) {
		this.constuctOrg = constuctOrg;
	}

	public String getBusinessScope() {
		return businessScope;
	}

	public void setBusinessScope(String businessScope) {
		this.businessScope = businessScope;
	}

	public String getMajorProduct() {
		return majorProduct;
	}

	public void setMajorProduct(String majorProduct) {
		this.majorProduct = majorProduct;
	}

	public String getMiddleProduct() {
		return middleProduct;
	}

	public void setMiddleProduct(String middleProduct) {
		this.middleProduct = middleProduct;
	}

	public String getProductionCapacity() {
		return productionCapacity;
	}

	public void setProductionCapacity(String productionCapacity) {
		this.productionCapacity = productionCapacity;
	}

	public String getMaterial() {
		return material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public String getGatePic() {
		return gatePic;
	}

	public void setGatePic(String gatePic) {
		this.gatePic = gatePic;
	}

	public String getWorkPic() {
		return workPic;
	}

	public void setWorkPic(String workPic) {
		this.workPic = workPic;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getLongitude() {
		return longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getDimensionality() {
		return dimensionality;
	}

	public void setDimensionality(String dimensionality) {
		this.dimensionality = dimensionality;
	}

	public String getSafetyOrg() {
		return safetyOrg;
	}

	public void setSafetyOrg(String safetyOrg) {
		this.safetyOrg = safetyOrg;
	}
	
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public boolean isDeleted() {
		return deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public Integer getSafetyId() {
		return safetyId;
	}

	public void setSafetyId(Integer safetyId) {
		this.safetyId = safetyId;
	}

	public String getZjId() {
		return zjId;
	}

	public void setZjId(String zjId) {
		this.zjId = zjId;
	}

	public String getGsId() {
		return gsId;
	}

	public void setGsId(String gsId) {
		this.gsId = gsId;
	}

	
	public Integer getIsMsds() {
		return isMsds;
	}

	public void setIsMsds(Integer isMsds) {
		this.isMsds = isMsds;
	}

	public Integer getIsGatherData() {
		return isGatherData;
	}

	public void setIsGatherData(Integer isGatherData) {
		this.isGatherData = isGatherData;
	}

	public String getNatinalRegulatoryCode1() {
		return natinalRegulatoryCode1;
	}

	public void setNatinalRegulatoryCode1(String natinalRegulatoryCode1) {
		this.natinalRegulatoryCode1 = natinalRegulatoryCode1;
	}

	public String getNatinalRegulatoryCode2() {
		return natinalRegulatoryCode2;
	}

	public void setNatinalRegulatoryCode2(String natinalRegulatoryCode2) {
		this.natinalRegulatoryCode2 = natinalRegulatoryCode2;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUuid() {
		return uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getProductionPurpose() {
		return productionPurpose;
	}

	public void setProductionPurpose(String productionPurpose) {
		this.productionPurpose = productionPurpose;
	}

	public String getRegOrgCode() {
		return regOrgCode;
	}

	public void setRegOrgCode(String regOrgCode) {
		this.regOrgCode = regOrgCode;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getPrincipalFirainDate() {
		return principalFirainDate;
	}

	public void setPrincipalFirainDate(Date principalFirainDate) {
		this.principalFirainDate = principalFirainDate;
	}

	public Integer getStorageState() {
		return storageState;
	}

	public void setStorageState(Integer storageState) {
		this.storageState = storageState;
	}

	public Integer getRecordState() {
		return recordState;
	}

	public void setRecordState(Integer recordState) {
		this.recordState = recordState;
	}

	public String getInSynFromDes() {
		return inSynFromDes;
	}

	public void setInSynFromDes(String inSynFromDes) {
		this.inSynFromDes = inSynFromDes;
	}

	public String getLegalTelephone() {
		return legalTelephone;
	}

	public void setLegalTelephone(String legalTelephone) {
		this.legalTelephone = legalTelephone;
	}

	public String getCoverState() {
		return CoverState;
	}

	public void setCoverState(String coverState) {
		CoverState = coverState;
	}

	public String getProvinceCode() {
		return provinceCode;
	}

	public void setProvinceCode(String provinceCode) {
		this.provinceCode = provinceCode;
	}

	public String getLinkPerson() {
		return linkPerson;
	}

	public void setLinkPerson(String linkPerson) {
		this.linkPerson = linkPerson;
	}

	public String getLinkPhone() {
		return linkPhone;
	}

	public void setLinkPhone(String linkPhone) {
		this.linkPhone = linkPhone;
	}

	public String getCreditGrade() {
		return creditGrade;
	}

	public void setCreditGrade(String creditGrade) {
		this.creditGrade = creditGrade;
	}

	public String getIdCard() {
		return idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Date getCreditCancelTime() {
		return creditCancelTime;
	}

	public void setCreditCancelTime(Date creditCancelTime) {
		this.creditCancelTime = creditCancelTime;
	}

	public Date getCancelTime() {
		return cancelTime;
	}

	public void setCancelTime(Date cancelTime) {
		this.cancelTime = cancelTime;
	}

	public String getEducation() {
		return education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	public Integer getIsHidden() {
		return isHidden;
	}

	public void setIsHidden(Integer isHidden) {
		this.isHidden = isHidden;
	}

	public Integer getCreditStatus() {
		return creditStatus;
	}

	public void setCreditStatus(Integer creditStatus) {
		this.creditStatus = creditStatus;
	}

	public String getDeptCode() {
		return deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	public int getFlag() {
		return flag;
	}

	public void setFlag(int flag) {
		this.flag = flag;
	}

	

	public Integer getIsSynchro() {
		return isSynchro;
	}

	public void setIsSynchro(Integer isSynchro) {
		this.isSynchro = isSynchro;
	}

	public String getSafetyMngPerson() {
		return safetyMngPerson;
	}

	public void setSafetyMngPerson(String safetyMngPerson) {
		this.safetyMngPerson = safetyMngPerson;
	}

	public String getSafetyMngPersonPhone() {
		return safetyMngPersonPhone;
	}

	public void setSafetyMngPersonPhone(String safetyMngPersonPhone) {
		this.safetyMngPersonPhone = safetyMngPersonPhone;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}


	public Long getIsSYN() {
		return isSYN;
	}

	public void setIsSYN(Long isSYN) {
		this.isSYN = isSYN;
	}

	public Long getSYN_NO() {
		return SYN_NO;
	}

	public void setSYN_NO(Long sYN_NO) {
		SYN_NO = sYN_NO;
	}

	public String getIsUpdate() {
		return isUpdate;
	}

	public void setIsUpdate(String isUpdate) {
		this.isUpdate = isUpdate;
	}

	public String getIS_HIDDEN() {
		return IS_HIDDEN;
	}

	public void setIS_HIDDEN(String iS_HIDDEN) {
		IS_HIDDEN = iS_HIDDEN;
	}

	public String getSecurityPrincipalPerson() {
		return securityPrincipalPerson;
	}

	public void setSecurityPrincipalPerson(String securityPrincipalPerson) {
		this.securityPrincipalPerson = securityPrincipalPerson;
	}

	public String getSecurityPrincipalTel() {
		return securityPrincipalTel;
	}

	public void setSecurityPrincipalTel(String securityPrincipalTel) {
		this.securityPrincipalTel = securityPrincipalTel;
	}

	public String getAqscId() {
		return aqscId;
	}

	public void setAqscId(String aqscId) {
		this.aqscId = aqscId;
	}

	/**
	 * @return the isHighRiskWork
	 */
	public String getIsHighRiskWork() {
		return isHighRiskWork;
	}

	/**
	 * @param isHighRiskWork the isHighRiskWork to set
	 */
	public void setIsHighRiskWork(String isHighRiskWork) {
		this.isHighRiskWork = isHighRiskWork;
	}

	/**
	 * @return the highRiskWork
	 */
	public String getHighRiskWork() {
		return highRiskWork;
	}

	/**
	 * @param highRiskWork the highRiskWork to set
	 */
	public void setHighRiskWork(String highRiskWork) {
		this.highRiskWork = highRiskWork;
	}

	/**
	 * @return the hiddenCompanyDate
	 */
	public Date getHiddenCompanyDate() {
		return hiddenCompanyDate;
	}

	/**
	 * @param hiddenCompanyDate the hiddenCompanyDate to set
	 */
	public void setHiddenCompanyDate(Date hiddenCompanyDate) {
		this.hiddenCompanyDate = hiddenCompanyDate;
	}

	
	
}
