package com.safetys.nbyhpc.domain.model;

import java.io.File;

import com.safetys.nbyhpc.domain.model.base.DaBaseModel;
import com.safetys.nbyhpc.util.FileUpload;

// Generated 2012-11-6 15:59:30 by Hibernate Tools 3.2.0.b9

/**
 * TCoreImage generated by hbm2java
 */
public class TCoreImage extends DaBaseModel implements java.io.Serializable {

	
	/**
	 * 企业基础信息子表(图片库)
	 */
	private static final long serialVersionUID = -81478436205710810L;
	
	private TCoreCompany coreCompany;
	
	private String num;//文件编号
	
	private String name;//文件名
	
	private File file;// 文件对象
	
	private String fileFileName;//上传过程中得到的文件名
	
	private String fileContentType;//上传过程中得到的文件类型
	
	private String path;//文件路径
	
	private Long size;//文件大小
	
	private String type;//文件类型
	
	private String fileOriginalName;//文件原名称
	
	private String fileDescription; //图片说明
	
	private Long userId;
	
	private String[] allowType = FileUpload.ALLOW_TYPE_JPG;
	
	public TCoreImage() {
		
	}
	
	public TCoreImage(Long id) {
		super(id);
	}

	public TCoreCompany getCoreCompany() {
		return coreCompany;
	}

	public void setCoreCompany(TCoreCompany coreCompany) {
		this.coreCompany = coreCompany;
	}

	public File getFile() {
		return file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public String getFileFileName() {
		return fileFileName;
	}

	public void setFileFileName(String fileFileName) {
		this.fileFileName = fileFileName;
	}

	public String getFileContentType() {
		return fileContentType;
	}

	public void setFileContentType(String fileContentType) {
		this.fileContentType = fileContentType;
	}

	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Long getSize() {
		return size;
	}

	public void setSize(Long size) {
		this.size = size;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getFileOriginalName() {
		return fileOriginalName;
	}

	public void setFileOriginalName(String fileOriginalName) {
		this.fileOriginalName = fileOriginalName;
	}

	public String getFileDescription() {
		return fileDescription;
	}

	public void setFileDescription(String fileDescription) {
		this.fileDescription = fileDescription;
	}

	public String[] getAllowType() {
		return allowType;
	}

	public void setAllowType(String[] allowType) {
		this.allowType = allowType;
	}

	public String getNum() {
		return num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}
}
