package com.safetys.nbyhpc.domain.model;

// Generated 2011-1-4 15:28:28 by Hibernate Tools 3.2.0.b9

import com.safetys.nbyhpc.domain.model.base.DaBaseModel;

/**
 * WhAccident generated by hbm2java
 */
public class WhAccident extends DaBaseModel {

	private WhCompanyInfo companyInfo;

	private Integer type;//事故类型

	private double lost;//损失

	private Integer hurtType;//伤亡类型

	private Integer dead;//死亡人数

	private Integer hurt;//受伤人数

	private String mainCause;//事故原因

	private String processResult;//处理结果
	
	private Long userId;

	public WhAccident() {
	}

	public WhCompanyInfo getCompanyInfo() {
		return companyInfo;
	}

	public void setCompanyInfo(WhCompanyInfo companyInfo) {
		this.companyInfo = companyInfo;
	}

	public Integer getDead() {
		return dead;
	}

	public void setDead(Integer dead) {
		this.dead = dead;
	}

	public Integer getHurt() {
		return hurt;
	}

	public void setHurt(Integer hurt) {
		this.hurt = hurt;
	}

	public Integer getHurtType() {
		return hurtType;
	}

	public void setHurtType(Integer hurtType) {
		this.hurtType = hurtType;
	}

	public double getLost() {
		return lost;
	}

	public void setLost(double lost) {
		this.lost = lost;
	}

	public String getMainCause() {
		return mainCause;
	}

	public void setMainCause(String mainCause) {
		this.mainCause = mainCause;
	}

	public String getProcessResult() {
		return processResult;
	}

	public void setProcessResult(String processResult) {
		this.processResult = processResult;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

}
